spring:
  profiles:
    active: pro
  datasource:
    username: root
    password: 9527
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhiwan?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&serverTimezone=GMT%2B8
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true